name: jup
description: "A Naam Jup application which is very helpful for devoties"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.2.0      # or provider if you prefer Provider
  shared_preferences: ^2.0.15
  uuid: ^3.0.6
  # intl: ^0.18.0
  intl: ^0.20.2

  google_fonts: ^6.3.2
  cupertino_icons: ^1.0.8
  fl_chart: ^0.60.0   # <-- Keep this version
  table_calendar: ^3.0.9
  home_widget: ^0.8.1
  flutter_native_splash: ^2.4.7
  speech_to_text: ^7.3.0
  permission_handler: ^11.3.1
  awesome_notifications: ^0.10.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



#flutter pub run flutter_native_splash:create
flutter_native_splash:
  android: true
  ios: true
  color: "#FFF38B "
  image: assets/icon/transparent.png
  web_image_mode: contain

#  branding: assets/icon/branding.png
  # branding_bottom_padding_ios: 35
  # color_dark: "#332828"

  android_12:
    color: "#FFF38B "
    # color_dark: "#332828"
    image: assets/icon/transparent.png
    # image_scale: 0.3
    # branding: assets/icon/branding.png

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.jpg
    - assets/icon/mala_ring.png
    - assets/icon/branding.png
    - assets/audio/ram.mp3
    - assets/icon/transparent.png

